replicas: 1

image:
  pullPolicy: IfNotPresent
  repository: registry.mareshq.com/lab/next-isr-bug
  tag: latest
  pullSecrets: []

service:
  type: ClusterIP
  port: 80
  portName: http
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: www.example.com
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: "1"
    memory: 1Gi
    ephemeral-storage: 256Mi
  requests:
    cpu: 500m
    memory: 1Gi
    ephemeral-storage: 256Mi

config:
  suppressGoogleAnalytics: true
  apiKey: "xxx"

  cms:
    apiURL: "https://strapi.example.com/api"
    apiToken: "xxx"

  cache:
    size: 256Mi # must be less than or equal to the ephemeral-storage limit

cron:
  refreshBlog:
    enabled: false
    schedule: "0 5 * * *"
    image: "curlimages/curl:7.76.1"
