apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  NODE_ENV: "production"
  PORT: {{ .Values.service.targetPort | quote }}
  HOSTNAME: "0.0.0.0"
  SUPPRESS_GOOGLE_ANALYTICS: {{ .Values.config.suppressGoogleAnalytics | quote }}
  CMS_API_URL: {{ .Values.config.cms.apiURL | quote }}
