{{- if .Values.cron.refreshBlog.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-refresh-blog
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "cronjob"
spec:
  schedule: "{{ .Values.cron.refreshBlog.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/component: "cronjob"
        spec:
          automountServiceAccountToken: false
          containers:
            - name: revalidate-blog
              image: "{{ .Values.cron.refreshBlog.image }}"
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - |
                  echo "Revalidating blog..."
                  curl --silent --fail-with-body -X POST --header "X-API-KEY: ${API_KEY}" http://{{ .Release.Name }}:{{ .Values.service.targetPort }}/api/revalidate-blog
                  echo "Revalidation done."
                  echo "Sending request to /blog to warm up the cache..."
                  curl --silent --fail http://{{ .Release.Name }}:{{ .Values.service.targetPort }}/blog
                  echo "Cache warm up done."
              env:
                - name: API_KEY
                  value: {{ .Values.config.apiKey | quote }}
          restartPolicy: OnFailure
{{- end }}
